#!/usr/bin/env python3
"""
Helper script to guide through servo testing process.
"""

print("🔧 SERVO 1 TESTING GUIDE")
print("="*60)
print()
print("You have 3 test programs available:")
print()
print("1️⃣  test_servo1_full_sweep.ino")
print("   - Tests ONLY Servo 1 (Pin 11)")
print("   - Very slow sweep: 0° → 180° → 0°")
print("   - Takes ~20 seconds per cycle")
print("   - Best for seeing if Servo 1 moves at all")
print()
print("2️⃣  test_both_servos_compare.ino")
print("   - Tests BOTH servos simultaneously")
print("   - Same movements for both")
print("   - Compare if Servo 1 behaves like Servo 2")
print("   - Best for diagnosing if Servo 1 is faulty")
print()
print("3️⃣  test_swap_servos.ino")
print("   - Tests Servo 1 hardware on Pin 10 (known working)")
print("   - Requires physically swapping servo connections")
print("   - Best for confirming if Servo 1 hardware is broken")
print()
print("="*60)
print("📋 RECOMMENDED TESTING ORDER:")
print("="*60)
print()
print("Step 1: Upload test_servo1_full_sweep.ino")
print("        - Watch Servo 1 very carefully")
print("        - Look for ANY movement, even tiny")
print("        - Open Serial Monitor to see position updates")
print()
print("Step 2: If no movement, upload test_both_servos_compare.ino")
print("        - Watch both servos")
print("        - Servo 2 should move (we know it works)")
print("        - Does Servo 1 move at all?")
print()
print("Step 3: If still no movement, physically swap servos")
print("        - Disconnect both servos")
print("        - Connect Servo 1 to Pin 10")
print("        - Connect Servo 2 to Pin 11")
print("        - Upload test_swap_servos.ino")
print("        - If Servo 1 now works → Pin 11 is bad")
print("        - If Servo 1 still doesn't work → Servo 1 is faulty")
print()
print("="*60)
print("🔍 POSSIBLE ISSUES:")
print("="*60)
print()
print("❌ Servo 1 is mechanically stuck")
print("   → Try manually rotating the servo arm")
print()
print("❌ Servo 1 is not getting power")
print("   → Check 5V and GND connections")
print("   → Try external power supply")
print()
print("❌ Servo 1 is faulty/broken")
print("   → Replace with a new servo")
print()
print("❌ Pin 11 is not working")
print("   → Try Pin 6 or Pin 5 instead")
print()
print("❌ Not enough power for both servos")
print("   → Use external 5V power supply")
print("   → Don't power both servos from Arduino")
print()
print("="*60)
print()
input("Press Enter to close...")
